
<meta charset="<?php echo $view->getActiveCharset(); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="<?php echo $view->getHostLink(); ?>/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<!-- Round Date Selector CSS -->
<link href="<?php echo $view->getHostLink(); ?>/vendor/round-date-selector/round-date-selector.css" rel="stylesheet" type="text/css">

<!-- Main Style CSS -->
<link href="<?php echo $view->getHostLink(); ?>/vendor/main.css" rel="stylesheet" type="text/css">

<!-- jQuery JavaScript-->
<script src="<?php echo $view->getHostLink(); ?>/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap JavaScript -->
<script src="<?php echo $view->getHostLink(); ?>/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Round Date Selector JavaScript -->
<script src="<?php echo $view->getHostLink(); ?>/vendor/round-date-selector/round-date-selector.min.js"></script>
