<!DOCTYPE html>
<html lang="<?php echo $view->getActiveLanguage(); ?>">
<head>

    <title><?php echo $view->translate('PROGRAM_TITLE'); ?></title>

    <?php

    $view->includeTemplate('headersrc', array());

    ?>

</head>

<body>
    <?php

    $view->includeTemplate('modaldelete', array());

    ?>
    <div id="wrapper">
        <?php

        $view->includeTemplate('navbar', array());

        ?>
        <div id="page-wrapper">
            <div class="row">
                <div class="colh1-lg-12">
                    <div class="panel"></div>
                </div>
            </div>
            <div class="row">
                <?php
                if (\Fado\Model\Cache::get('message') != '') {
                ?>
                <div class="col-lg-12">
                    <p>
                        <button type="button" class="btn btn-outline btn-success"><?php echo $view->translate(\Fado\Model\Cache::get('message')); ?></button>
                    </p>
                </div>
                <?php
                }
                ?>
            </div>
            <?php

            $view->includeTemplate('invoicestable', array('list' => $invoices, 'allShops' => $allShops));

            ?>
            <?php
            $invoiceItems = (array) json_decode(\Fado\Model\Cache::get('activeInvoice'), true);
            if ($invoiceItems) {
                 $view->includeTemplate('invoiceview', array('invoices' => $invoiceItems, 'shop' => json_decode(\Fado\Model\Cache::get('InvoiceViewShopCustomer'), true), 'activeUser' => json_decode(\Fado\Model\Cache::get('InvoiceViewShopSeller'), true), 'inInvoiceView' => true, 'inPrintView' => false));
            }
            ?>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <script>
        $('.nav-pills a').click(function(){
            $(this).tab('show');
        });
        $('a[href*="invoice=<?php echo $invoices->current()['sid']; ?>"]').on('click', function(e) {
            $('#add-invoice-panel').css('display', 'none');
            $('#invoice-panel').css('display', 'block');
        });
     </script>

     <script>
         $('#modal-delete').on('show.bs.modal', function(e) {
            var activeForm = $(e.relatedTarget.form)
            var formInput = activeForm.serializeArray();
            formInput.push({name: 'delete', value: 'delete_invoice'});
            $('button#modal-confirm-delete').on('click', function(e) {
                $.ajax({
                    url: activeForm.action,
                    type: 'POST',
                    data: formInput,
                    success: function(data){
                        document.open();
                        document.write(data);
                        document.close();
                    }
                });
            });
         });
     </script>

</body>

</html>
