<?php

use \Fado\Model\Setting as Setting;

$vatOn = (bool) Setting::get('vat_on');
$bruttoMode = Setting::get('invoice_mode') == 'brutto';
$formMessages = json_decode(\Fado\Model\Cache::get('formStatus'), true);

?>
<div class="panel panel-grass">
    <div class="panel-heading invoice-heading">
        <?php echo $view->translate('INVOICES_TITLE'); ?>

        <?php
        if ($inInvoiceView && !$inPrintView && isset(current($invoices)['invoice_id'])) {
        ?>
        <div class="box-right">
            <a href="<?php echo $view->getRewriteURL(array('invoice' => current($invoices)['invoice_id'], 'print' => true), 'in'); ?>" class="invoice-tool"><span class="glyphicon glyphicon-print glyphicon-md"></span></a>

            <!--
            <a href="<?php echo $view->getRewriteURL(array('invoice' => current($invoices)['invoice_id'], 'pdf' => true), 'in'); ?>" class="invoice-tool"></a>
            -->
        </div><!--
        <div class="col-xs-4 box-right">
            <form method="POST" name="mailto" action="<?php echo $view->getRewriteURL(array('invoice' => current($invoices)['invoice_id'], 'mail' => true), 'in'); ?>">
                <div class="form-group" style="padding: 0;">
                    <?php if (isset($formMessages['mailto'])) { ?>
                    <label class="control-label box-left invoice-tool-error" for="mailto"><?php echo $view->translate($formMessages['mailto']); ?>&nbsp;</label>
                    <?php } ?>
                    <div class="input-group">
                        <input name="mailto" class="form-control" placeholder="mail@home.my" value="">
                        <span class="input-group-btn">
                            <button type="submit" name="submit" value="submit" class="btn btn-secondary btn-primary"></button>
                        </span>
                    </div>
                </div>
            </form>
        </div>-->
        <?php
        }
        ?>
    </div>
    <div class="panel-body">
        <?php
        if ($shop) {
        ?>
        <div class="col-xs-5">
            <!--<h4><?php echo $this->translate('INVOICES_LABEL_CUSTOMER'); ?></h4>-->
            <address>
                <strong><?php echo $shop['description']; ?></strong><br>
                <?php echo $shop['street'] . ' ' . $shop['streetnr']; ?><br>
                <?php echo $shop['zip'] . ' ' . $shop['city'] . ' ' . $shop['country']; ?><br>
            </address>
            <address>
                <a href="tel:<?php echo $shop['phone']; ?>"><?php echo $shop['phone']; ?></a><br>
                <a href="mailto:<?php echo $shop['email']; ?>"><?php echo $shop['email']; ?></a><br><br>
            </address>
        </div>
        <?php
        }
        ?>
        <div class="col-xs-5 pull-right">
            <!--<h4><?php echo $this->translate('INVOICES_LABEL_SELLER'); ?></h4>-->
            <address>
                <strong><?php echo $activeUser['description']; ?></strong><br>
                <?php echo $activeUser['street'] . ' ' . $activeUser['streetnr']; ?><br>
                <?php echo $activeUser['zip'] . ' ' . $activeUser['city'] . ' ' . $activeUser['country']; ?><br>
            </address>
            <address>
                <a href="tel:<?php echo $activeUser['shop_phone']; ?>"><?php echo $activeUser['shop_phone']; ?></a><br>
                <a href="mailto:<?php echo $activeUser['shop_email']; ?>"><?php echo $activeUser['shop_email']; ?></a><br><br>
            </address>
        </div>
        <?php
            if (isset(current($invoices)['invoice_id'])) {
        ?>
        <div class="col-xs-5">
            <p>
            <strong><?php echo $this->translate('INVOICES_LABEL_ID'); ?></strong> <?php echo current($invoices)['invoice_id']; ?><br>
            <strong><?php echo $this->translate('INVOICES_LABEL_DATE'); ?></strong> <?php echo  $view->formatDateTime(current($invoices)['inv_created']); ?><br>
            </p>
        </div>
        <?php
            }
        ?>

        <div class="row col-md-12">
            <table class="table table-striped table-bordered table-hover no-footer" role="grid"  style="width: 100%;">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('WAREHOUSE_ITEMS_LABEL_POS'); ?></th>
                        <th><?php echo $this->translate('WAREHOUSE_ITEMS_LABEL_INFORMATION'); ?></th>
                        <th><?php echo $this->translate('INVOICES_LABEL_QUANTITY'); ?></th>
                        <?php if ($vatOn) { ?><th><?php echo $this->translate('WAREHOUSE_ITEMS_LABEL_TAX_RATE'); ?></th><?php } ?>
                        <th><?php echo $this->translate('INVOICES_LABEL_PRICE'); ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php
                    $sum = 0.0;
                    $sumVAT = 0.0;
                    $pos = 1;
                    foreach($invoices as $item) {
                        $itemSum  = (float)$item['item_amount'] * $item['price_unit'];
                        if ($vatOn) {
                            $itemVAT = (float)$view->calculateVAT($itemSum, $item['tax_rate']);
                            $sumVAT += $itemVAT;
                        }
                        $itemCost = (float)$item['price_unit'];
                        if ($item['cut_rate'] != 0) {
                            $diff = round((float)$itemCost * $item['cut_rate'] / 100, 2);
                            $itemSum -= (float)$item['item_amount'] * $diff;
                        }
                        $sum += $itemSum;
                    ?>
                    <tr>
                        <td><?php echo $pos; ?></td>
                        <td><?php echo $item['name']?></td>
                        <td>
                        <?php
                            echo $item['item_amount'] . '&nbsp;' . $this->translate('INVOICE_MULTIPLIER') . '&nbsp;' . $item['unit'] . '&nbsp;' . $this->translate('INVOICE_PER_ITEM') . '&nbsp;' . $view->escapeString($view->formatNumber($itemCost)) . '&nbsp;' . Setting::getActiveCurrency();
                            if ($item['cut_rate'] != 0) {
                                echo '&nbsp;-&nbsp;' . $view->escapeString($item['cut_rate']) . '%&nbsp;=&nbsp;' . $view->escapeString($view->formatNumber($itemCost - $diff)) . '&nbsp;' . Setting::getActiveCurrency();
                            }
                        ?>
                        </td>
                        <?php if ($vatOn) { ?>
                        <td><?php echo intval($item['tax_rate']) . '%&nbsp;' . $this->translate('INVOICE_MULTIPLIER') . '&nbsp;' . $view->escapeString($view->formatNumber($itemSum)) . '&nbsp;' . Setting::getActiveCurrency() . '&nbsp;=&nbsp;' . $view->formatNumber($itemVAT) . '&nbsp;' . Setting::getActiveCurrency(); ?>
                        </td>
                        <?php } ?>
                        <td><?php echo $view->escapeString($view->formatNumber($itemSum)) . '&nbsp;' . Setting::getActiveCurrency(); ?></td>
                        </tr>
                    <?php
                       $pos++;
                    }
                    ?>
                    <?php if ($vatOn && !$bruttoMode) { ?>
                    <tr>
                        <td colspan="<?php echo ($vatOn) ? 3 : 2; ?>"></td>
                        <td><strong><?php echo $this->translate('INVOICES_LABEL_SUM_NETTO'); ?></strong></td>
                        <td><?php echo  $view->escapeString($view->formatNumber($sum)) . '&nbsp;' . Setting::getActiveCurrency(); ?></td>
                    </tr>
                    <?php } ?>
                    <?php if ($vatOn) { ?>
                    <tr>
                        <td colspan="<?php echo ($vatOn) ? 3 : 2; ?>"></td>
                        <td><strong><?php echo $this->translate(($bruttoMode) ? 'INVOICES_LABEL_VAT_BRUTTO' : 'INVOICES_LABEL_VAT_NETTO'); ?></strong></td>
                        <td><?php echo  $view->escapeString($view->formatNumber($sumVAT)) . '&nbsp;' . Setting::getActiveCurrency(); ?></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <td colspan="<?php echo ($vatOn) ? 3 : 2; ?>"></td>
                        <td><strong><?php echo $this->translate('INVOICES_LABEL_SUM_BRUTTO'); ?></strong></td>
                    <?php if ($vatOn && $bruttoMode) { ?>
                        <td><?php echo $view->escapeString($view->formatNumber($sum)) . '&nbsp;' . Setting::getActiveCurrency(); ?></td>
                    <?php } ?>
                    <?php if (!$vatOn || ($vatOn && !$bruttoMode)) { ?>
                        <td><?php echo $view->escapeString($view->formatNumber($sum + $sumVAT)) . '&nbsp;' . Setting::getActiveCurrency(); ?></td>
                    <?php } ?>
                    </tr>
                </tbody>
            </table>
        </div>
        <?php
        if (!$inInvoiceView && !$inPrintView) {
        ?>
        <div class="row col-md-12">
            <form id="invoice_page2"  method="POST" action="<?php echo $view->getFullLink(); ?>">
                <div class="row col-md-12">
                    <div class="col-xs-12">
                        <button type="submit" name="save_invoice" value="save_invoice" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> <?php echo $view->translate('SAVE'); ?></button>
                        <button type="submit" name="cancel_invoice" value="cancel_invoice" class="btn btn-default"><span class="glyphicon glyphicon-minus"></span><?php echo $view->translate('CANCEL'); ?></button>
                    </div>
                </div>
            </form>
        </div>
        <?php
        }
        ?>
        <?php
        if ($inInvoiceView && !$inPrintView) {
        ?>
        <div class="row col-md-12">
            <form  method="POST" action="<?php echo $view->getFullLink(); ?>">
                    <input type="hidden" name="id" value="<?php echo current($invoices)['invoice_id']; ?>" />
                    <div class="form-group">
                        <label><?php echo $view->translate('WAREHOUSE_ITEM_LABEL_IS_PAYED'); ?></label>
                        <div class="checkbox-inline">
                            <input name="is_payed" type="checkbox" class="form-control" value="1" <?php echo (current($invoices)['is_payed'] == '1') ? 'checked="checked"' : ''; ?> <?php echo ($inPrintView) ? 'disabled="disabled" class="disabled"' : ''; ?>>
                        </div>
                    </div>
            <?php
            if (!$inPrintView) {
            ?>
                    <div class="form-group col-xs-12">
                        <button type="submit" name="submit" value="save_invoice" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> <?php echo $view->translate('SAVE'); ?></button>
                        <button type="button" name="delete" value="delete_invoice" class="btn btn-default" data-toggle="modal" data-target="#modal-delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <?php echo $view->translate('DELETE'); ?></button>
                    </div>
            <?php
            }
            ?>
            </form>
        </div>
        <?php
        }
        ?>
    </div>
</div>
