<!DOCTYPE html>
<html lang="<?php echo $view->getActiveLanguage(); ?>">

<head>

    <title><?php echo $view->translate('PROGRAM_TITLE'); ?></title>

    <?php

    $view->includeTemplate('headersrc', array());

    ?>

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $view->translate('LOGIN_TEXT'); ?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <?php
                            if (\Fado\Model\Cache::get('message') != '' && \Fado\Model\Cache::get('message') != 'INVALID_AUTH_TOO_MANY_ATTEMPTS') {
                            ?>
                            <div class="col-lg-12">
                                <p>
                                    <button type="button" class="btn btn-danger"><?php echo $view->translate(\Fado\Model\Cache::get('message')); ?></button>
                                </p>
                            </div>
                            <?php
                            }

                            if (\Fado\Model\Cache::get('message') == 'INVALID_AUTH_TOO_MANY_ATTEMPTS') {
                            ?>
                            <div class="col-lg-12">
                                <p>
                                    <button type="button" class="btn btn-danger"><?php echo $view->translate(\Fado\Model\Cache::get('message'), \Fado\Model\Setting::get('maximum_login_attempts')); ?></button>
                                </p>
                            </div>
                            <?php
                            }
                            ?>
                        </div>
                        <form  action="/" method="post">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="<?php echo $view->translate('LOGIN_USERNAME'); ?>" name="email" type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="<?php echo $view->translate('LOGIN_PASSWORD'); ?>" name="password" type="password">
                                </div>
                                <!--<div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="<?php echo $view->translate('LOGIN_REMEMBER_ME'); ?>"><?php echo $view->translate('LOGIN_REMEMBER_ME'); ?>
                                    </label>
                                </div>-->
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-submit btn-block"><?php echo $view->translate('BUTTON_LOGIN'); ?></button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>
