<?php
$isMemCacheActive = (bool)\Fado\Model\Setting::get('memcache_on');
?>
<html lang="<?php echo $view->getActiveLanguage(); ?>">
<head>

    <title><?php echo $view->translate('PROGRAM_TITLE'); ?></title>

    <?php

    $view->includeTemplate('headersrc', array());

    ?>

</head>

<body>
    <div id="wrapper">
        <?php

        $view->includeTemplate('navbar', array());

        ?>
        <div id="page-wrapper">

            <div class="row">


                    <div class="panel panel-fire">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <a href="<?php echo $view->getRewriteUrl(array(), 'st'); ?>" style="background-color: #ff5353e6;"><span class="glyphicon glyphicon-arrow-left glyphicon-md"></span></a>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <h3> <?php echo $view->translate('SERVER_INFO'); ?></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                if($isMemCacheActive) {
                ?>
                <div class="col-lg-4">
                    <div class="panel panel-sun">
                        <?php
                            foreach(\Fado\Model\MemCache::status() as $server => $status) {
                        ?>
                        <div class="panel-heading">
                            <?php echo $view->translate('PHP_MEMCACHE_STATUS'); ?>
                        </div>
                        <div class="panel-body">
                            <table class="table table-striped table-bordered table-hover no-footer" role="grid" style="width: auto;">
                                <tbody>
                                    <tr>
                                        <th><?php echo $view->translate('PHP_MEMCACHE_KEY'); ?></th>
                                        <th><?php echo $view->translate('PHP_MEMCACHE_VALUE'); ?></th>
                                    </tr>
                        <?php
                                foreach($status as $key => $data) {
                        ?>
                                    <tr>
                                        <td><?php echo $key; ?></td>
                                        <td><?php echo $data; ?></td>
                                    </tr>
                        <?php
                                }
                            }
                        ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <?php
                }
                ?>
                <div class="col-lg-<?php echo ($isMemCacheActive) ? '8' : '12'; ?>">
                    <div class="panel panel-grass">
                        <div class="panel-heading">
                            <?php echo $view->translate('PHP_INFO_HEADING'); ?>
                        </div>
                        <div class="panel-body">
                        <?php phpinfo(); ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</body>

</html>
