<?php
$activeTab = \Fado\Model\Cache::get('activeTab');
?>
<div class="row" id="shop-panel" style="display: block;">
    <div class="col-lg-12">
        <div class="panel panel-sun">
            <div class="panel-heading">
                <?php echo $view->translate('SHOP_PANEL_HEADING'); ?>: <?php echo $activeShop['description']; ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="nav nav-pills">
                    <li id="SHOP_TAB_MAPID" class="active"><a data-tab-id="SHOP_TAB_MAP" data-toggle="tab" href="#SHOP_TAB_MAP"><?php echo $view->translate('SHOP_PANEL_MAP'); ?></a></li>
                    <li id="SHOP_TAB_ADDRESSID" class="active"><a data-tab-id="SHOP_TAB_ADDRESS" data-toggle="tab" href="#SHOP_TAB_ADDRESS"><?php echo $view->translate('SHOP_PANEL_ADDRESS'); ?></a></li>
        <?php
            if ($view->userRights->isAllowed('sh', \Fado\Controller\RouterRights::$WRITE)) {
        ?>
                    <li id="SHOP_TAB_FORMID" class="active"><a data-tab-id="SHOP_TAB_FORM" data-toggle="tab" href="#SHOP_TAB_FORM"><?php echo $view->translate('SHOP_PANEL_DATA'); ?></a></li>
                    <li id="SHOP_TAB_VEHICLEID" class="active"><a data-tab-id="SHOP_TAB_VEHICLE" data-toggle="tab" href="#SHOP_TAB_VEHICLE"><?php echo $view->translate('SHOP_PANEL_VEHICLE'); ?></a></li>
                    <li id="SHOP_TAB_USERID" class="active"><a data-tab-id="SHOP_TAB_USER" data-toggle="tab" href="#SHOP_TAB_USER"><?php echo $view->translate('SHOP_PANEL_USER'); ?></a></li>
        <?php
            }
        ?>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div id="SHOP_TAB_ADDRESS" class="tab-pane fade in active" role="tabpanel">
                            <address>
                                <strong><?php echo $activeShop['description']; ?></strong><br>
                                <?php echo $activeShop['street'] . ' ' . $activeShop['streetnr']; ?><br>
                                <?php echo $activeShop['zip'] . ' ' . $activeShop['city'] . ' ' . $activeShop['country']; ?><br>
                            </address>
                            <address>
                                <a href="tel:<?php echo $activeShop['phone']; ?>"><?php echo $activeShop['phone']; ?></a><br>
                                <a href="mailto:<?php echo $activeShop['email']; ?>"><?php echo $activeShop['email']; ?></a><br><br>
                                <?php
                                    $openingHours = json_decode($activeShop['opening_hours'], true);
                                    foreach ($openingHours as $key => $hour) {
                                        $times = explode('-', $hour['range']);
                                        $openingHours[$key]['start'] = $times[0];
                                        $openingHours[$key]['stop'] = $times[1];
                                        $formattedRange = $view->formatDateTime('2017-01-' . ($openingHours[$key]['start'] + 2), '%a') . ' - ' . $view->formatDateTime('2017-01-' . ($openingHours[$key]['stop'] + 2), '%a');
                                        if ($times[0] == $times[1]) {
                                            $formattedRange = $view->formatDateTime('2017-01-' . ($openingHours[$key]['start'] + 2), '%a');
                                        }
                                        ?>
                                <b><?php echo $formattedRange; ?></b>
                                <?php echo $view->formatTime($openingHours[$key]['open']) . ' - ' .  $view->formatTime($openingHours[$key]['close']); ?>
                                <?php
                                    }
                                ?>
                                <br><br>
                                <?php echo $view->decodeHtmlEntities(json_decode($activeShop['information'])); ?>
                                <br><br>
                                <?php echo $view->DDtoDMS($activeShop['lng'], 'lng') . ' ' . $view->DDtoDMS($activeShop['lat'], 'lat'); ?>
                            </address>
                    </div>
                    <div id="SHOP_TAB_MAP" class="tab-pane fade in active" role="tabpanel">
                        <h4><?php echo $view->translate('SHOP_PANEL_MAP'); ?></h4>
                        <div class="col-lg-9">
                            <div class="panel panel-default">
                                <div id="map" class="map" style="height: 600px; width:100%;"></div>
                            </div>
                        </div>
        <?php
            if ($view->userRights->isAllowed('sh', \Fado\Controller\RouterRights::$WRITE)) {
        ?>
                        <div class="col-lg-3">
                            <form id="shop2locationform" method="POST" action="<?php echo $view->getFullLink(); ?>">
                                <input type="hidden" name="save_coords" value="save_coords"/>
                                <input type="hidden" name="shop" value="<?php echo $activeShop['sid']; ?>"/>
                                <div class="form-group">
                                    <label><?php echo $view->translate('SHOP_PANEL_DATA_COORDS_LNG'); ?></label>
                                    <input id="shop_coordinates_lng" name="shop_coordinates_lng" type="text" value="<?php echo $activeShop['lng']; ?>"/>
                                </div>
                                <div class="form-group">
                                    <label><?php echo $view->translate('SHOP_PANEL_DATA_COORDS_LAT'); ?></label>
                                    <input id="shop_coordinates_lat" name="shop_coordinates_lat" type="text" value="<?php echo $activeShop['lat']; ?>"/>
                                </div>
                                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> <?php echo $view->translate('SAVE'); ?></button>
                            </form>
                        </div>
        <?php
            }
        ?>
                    </div>
        <?php
            if ($view->userRights->isAllowed('sh', \Fado\Controller\RouterRights::$WRITE)) {
        ?>
                    <div id="SHOP_TAB_FORM" class="tab-pane fade in active" role="tabpanel">
                        <h4><?php echo $view->translate('SHOP_PANEL_DATA'); ?></h4>
                        <?php $view->includeTemplate('shopform', array('activeShop' => $activeShop, 'openNewShop' => false)); ?>
                    </div>
                    <div id="SHOP_TAB_VEHICLE" class="tab-pane fade in active" role="tabpanel">
                        <?php

                        $view->includeTemplate('vehicletabtable', array('assignedVehicles' => $assignedVehicles));
                        $view->includeTemplate('selectors/vehicles2shop', array('activeShop' =>  $activeShop, 'assignedVehicles' => $assignedVehicles, 'allVehicles' => $allVehicles));

                        ?>
                    </div>
                    <div id="SHOP_TAB_USER" class="tab-pane fade in active" role="tabpanel">
                        <?php

                        $view->includeTemplate('usertabtable', array('assignedUsers' => $assignedUsers));
                        $view->includeTemplate('selectors/user2shop', array('activeShop' =>  $activeShop, 'assignedUsers' => $assignedUsers, 'allUsers' => $allUsers));

                        ?>
                    </div>
        <?php
            }
        ?>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
