<?php
$formMessages = (array) json_decode(\Fado\Model\Cache::get('formStatus'));
if ($activeUser == null) {
    $activeUser = (array) json_decode(\Fado\Model\Cache::get('newFormData2'));
}
if ($openNewUserForm || empty($activeUser) && empty($formMessages)) {
    $formMessages = array();
    $activeUser = array_fill_keys(USER_DATA_FIELDS, '');
}
if ($view->userRights->isAllowed('us', \Fado\Controller\RouterRights::$READ)) {
    $disabled = 'disabled';
} else {
    $disabled = '';
}
?>
<div class="col-lg-6">
    <form  action="<?php echo $view->getFullLink(); ?>" method="POST">
        <input type="hidden" name="id" value="<?php echo $activeUser['sid']; ?>">
        <div class="form-group <?php echo (isset($formMessages['name'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('USER_LABEL_NAME'); ?></label>
            <?php if (isset($formMessages['name'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['name']); ?></label>
            <?php } ?>
    <!--        <input name="name" class="form-control" placeholder="" value="<?php echo $activeUser['name']; ?>">-->
    <!--        <p class="form-control-static"><?php echo $activeUser['name']; ?></p>-->
            <input name="name" class="form-control" value="<?php echo $activeUser['name']; ?>" <?php echo ($openNewUserForm != '1') ? 'readonly' : ''; ?> type="text" <?php echo $disabled; ?>>
        </div>
        <div class="form-group <?php echo (isset($formMessages['pwd'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('USER_LABEL_PWD'); ?></label>
            <?php if (isset($formMessages['pwd'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['pwd']); ?></label>
            <?php } ?>
            <div class="form-group input-group">
                <span class="input-group-addon">***</span>
                <input name="pwd" type="password" onfocus="javascript:this.value=''" placeholder="<?php echo $activeUser['pwd']; ?>" class="form-control" value="" <?php echo $disabled; ?>>
            </div>
        </div>
        <div class="form-group <?php echo (isset($formMessages['active'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('USER_LABEL_ACTIVE'); ?></label>
            <?php if (isset($formMessages['active'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['active']); ?></label>
            <?php } ?>
            <div class="checkbox-inline">
                <input name="active" type="checkbox" class="form-control" placeholder="" value="1" <?php echo ($activeUser['active'] == '1') ? 'checked="checked"' : ''; ?> <?php echo $disabled; ?>>
            </div>
        </div>
        <div class="form-group <?php echo (isset($formMessages['phone'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('USER_LABEL_PHONE'); ?></label>
            <?php if (isset($formMessages['phone'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['phone']); ?></label>
            <?php } ?>
            <div class="form-group input-group">
                <span class="input-group-addon">&nbsp;🕻&nbsp;</span>
                <input name="phone" class="form-control" placeholder="" value="<?php echo $activeUser['phone']; ?>" <?php echo $disabled; ?>>
            </div>
        </div>
        <div class="form-group <?php echo (isset($formMessages['email'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('USER_LABEL_EMAIL'); ?></label>
            <?php if (isset($formMessages['email'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['email']); ?></label>
            <?php } ?>
            <div class="form-group input-group">
                <span class="input-group-addon">@</span>
                <input name="email" class="form-control" placeholder="" value="<?php echo $activeUser['email']; ?>" <?php echo $disabled; ?>>
            </div>
        </div>
        <div class="form-group <?php echo (isset($formMessages['data'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('USER_LABEL_DATA'); ?></label>
            <?php if (isset($formMessages['data'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['data']); ?></label>
            <?php } ?>
            <textarea id="<?php echo (!$openNewUserForm) ? 'editor-1' : 'editor-new'; ?>" name="<?php echo (!$openNewUserForm) ? 'editor-1' : 'editor-new'; ?>" class="form-control" rows="3" <?php echo $disabled; ?>>
                <?php echo $view->decodeHtmlEntities(json_decode($activeUser['data'])); ?>
            </textarea>
        </div>
        <div class="form-group <?php echo (isset($formMessages['email'])) ? 'has-error' : ''; ?>">
        <?php
            if (in_array($activeUser['birthday'], array('1900-01-01', '0000-00-00', '', null))) {
                $activeUser['birthday'] = '2019-04-15';
            }
            $view->includeTemplate('selectors/datetime', array('name_date' => 'birthday', 'date' => true, 'clock' => false, 'label_date' => 'USER_LABEL_BIRTHDAY', 'label_clock' => '', 'year' => substr($activeUser['birthday'], 0 , 4), 'month' => substr($activeUser['birthday'], 5, 2), 'day' => substr($activeUser['birthday'], 8, 2), 'calendarcontainer' => ($openNewUserForm) ? 'birthdaynew' : 'birthday', 'clockcontainer' => ''));
        ?>
        </div>
        <div class="clear"></div>
        <button type="submit" name="submit" value="save_user" class="btn btn-default" <?php echo $disabled; ?> ><span class="glyphicon glyphicon-ok"></span> <?php echo $view->translate('SAVE'); ?></button>
        <?php
        if ($openNewUserForm != '1'
            && !in_array($activeUser['name'], ADMIN_USERS)
            && $view->getController('Source\Users')->getLoggedInUser()['name'] != $activeUser['name']) {
        ?>
        <button type="button" name="delete" value="delete_user" class="btn btn-default" <?php echo $disabled; ?>  data-toggle="modal" data-target="#modal-delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <?php echo $view->translate('DELETE'); ?></button>
        <?php } ?>
    </form>
</div>
