<!DOCTYPE html>
<html lang="<?php echo $view->getActiveLanguage(); ?>">
<head>

    <title><?php echo $view->translate('PROGRAM_TITLE'); ?></title>

    <?php

    $view->includeTemplate('headersrc', array());

    ?>

    <!-- ckeditor JavaScript -->
    <script src="<?php echo $view->getHostLink(); ?>/vendor/ckeditor/ckeditor.js"></script>

    <!-- ckeditor config JavaScript -->
    <script src="<?php echo $view->getHostLink(); ?>/vendor/ckeditor/config.js"></script>

</head>

<body>
    <?php

    $view->includeTemplate('modaldelete', array());

    ?>
    <div id="wrapper">
        <?php

        $view->includeTemplate('navbar', array());

        ?>
        <div id="page-wrapper">
            <!-- /.row -->
            <div class="row">
                <div class="colh1-lg-12">
                    <div class="panel">
                    </div>
                </div>
            </div>
            <div class="row">
                <?php
                if (\Fado\Model\Cache::get('message') != '') {
                ?>
                <div class="col-lg-12">
                    <p>
                        <button type="button" class="btn btn-outline btn-danger"><?php echo $view->translate(\Fado\Model\Cache::get('message')); ?></button>
                    </p>
                </div>
                <?php
                }
                ?>
            </div>
            <?php

            $openNewUserForm = \Fado\Model\Cache::get('openNewUserForm');
            $view->includeTemplate('usertable', array('user' => $user));

            ?>
            <div class="row" id="add-user-panel"  style="<?php echo ($openNewUserForm == '1') ? '' : 'display: none'; ?>">
                <div class="col-lg-12">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <?php echo $view->translate('USER_PANEL_HEADING'); ?>
                            <div class="input-group pull-right">
                                <form>
                                    <span class="input-group-btn">
                                        <button type="button" id="close-add-user" class="btn btn-xs btn-secondary btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
                                    </span>
                                </form>
                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <?php $view->includeTemplate('userform', array('activeUser' => null, 'openNewUserForm' => 1)); ?>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <?php
            if ($user->getActivePos() >= 1 && $openNewUserForm != '1') {
                $view->includeTemplate('usertabs', array('activeUser' => $user->current(), 'openNewUserForm' => $openNewUserForm, 'assignedShops' => $assignedShops, 'allShops' => $allShops));
            }
            ?>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <script>

        CKEDITOR.replace('editor-1');
        CKEDITOR.replace('editor-new');

        $('.nav-pills > li').each(function(i, e){
            var activeTab = '<?php echo \Fado\Model\Cache::get('activeTab'); ?>' + 'ID';
            if (e.id == activeTab) {
                $(e).addClass('active');
            } else {
                $(e).removeClass('active');
            }
        });

        $('.tab-content > div').each(function(i, e){
            var activeTab = '<?php echo \Fado\Model\Cache::get('activeTab'); ?>';
            if (e.id == activeTab) {
                $(e).addClass('active');
            } else {
                $(e).removeClass('active');
            }
        });

        $('.nav-pills a').click(function(){
            $(this).tab('show');
            $.ajax({
              url: '<?php echo $view->getHostLink(); ?>',
              method: 'POST',
              data: { page: 'aj', controller: 'tabs', id: $(this).data('tab-id')},
              dataType: 'JSON'
            }).done(function(msg) {
            });
        });

        $('a[href*="user=<?php echo $user->current()['sid']; ?>"]').on('click', function(e) {
            $('#add-user-panel').css('display', 'none');
            $('#user-panel').css('display', 'block');
        });

        $('#add-us, #close-add-user').on('click', function(e) {
            e.preventDefault();
            $('#add-user-panel, #user-panel').each(function() {
                $(this).toggle();
            });
        });

        $('#modal-delete').on('show.bs.modal', function(e) {
            var activeForm = $(e.relatedTarget.form)
            var formInput = activeForm.serializeArray();
            formInput.push({name: 'delete', value: 'delete_user'});
            $('button#modal-confirm-delete').on('click', function(e) {
                $.ajax({
                    url: activeForm.action,
                    type: 'POST',
                    data: formInput,
                    success: function(data){
                        document.open();
                        document.write(data);
                        document.close();
                    }
                });
            });
        });

     </script>

</body>

</html>
