<div class="colh1-lg-12">
    <div class="panel panel-default panel-blue">
        <div class="panel-heading">
            <div class="">
                <h4><?php echo $view->translate('SHOP_PANEL_USER'); ?></h4>
            </div>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body table-responsive table-bordered">
            <div class="form-inline dt-bootstrap no-footer">
                 <table class="table table-striped table-bordered table-hover no-footer" id="user-tab-table" role="grid" style="width: 100%;">
                    <thead>
                        <tr>
                        <?php

                        $columns = array('name', 'data');

                        foreach ($columns as $column) {
                        ?>
                            <th class="" tabindex="0" rowspan="1" colspan="1" aria-label=""><?php echo $view->translate('USER_LABEL_' . mb_strtoupper($column)); ?></th>
                        <?php
                        }
                        ?>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach($assignedUsers->get() as $user) {
                    ?>
                        <tr class="gradeA odd" >
                            <td class="sorting_1"><a href="<?php echo $view->getRewriteUrl(array('user' => $user['sid']), 'us'); ?>#user-panel"><?php echo $user['name']; ?></a></td>
                            <td class="sorting_1"><?php echo $view->decodeHtmlEntities(json_decode($user['data'])); ?></td>
                        </tr>
                    <?php
                        }
                    ?>
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="">
                        <div class="" role="status" aria-live="polite"><?php echo $assignedUsers->count(); ?> entries</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
