<?php
$activeTab = \Fado\Model\Cache::get('activeTab');
?>
<div class="row" id="vehicle-panel" style="display: block;">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <?php echo $view->translate('VEHICLE_PANEL_HEADING'); ?>: <?php echo $activeVehicle['name']; ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="nav nav-pills">
                    <li id="VEHICLE_TABID" class="active"><a data-tab-id='VEHICLE_TAB' data-toggle="tab" href="#VEHICLE_TAB"><?php echo $view->translate('VEHICLE_PANEL_DATA'); ?></a></li>
                <?php
                    if ($view->userRights->isAllowed('ve', \Fado\Controller\RouterRights::$WRITE)) {
                ?>
                     <li id="VEHICLE_TAB_SHOPID" class="active"><a data-tab-id="VEHICLE_TAB_SHOP" data-toggle="tab" href="#VEHICLE_TAB_SHOP"><?php echo $view->translate('VEHICLE_PANEL_SHOPS'); ?></a></li>
                <?php
                    }
                ?>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="VEHICLE_TAB" role="tabpanel">
                        <h4><?php echo $view->translate('VEHICLE_PANEL_DATA'); ?></h4>
                        <?php $view->includeTemplate('vehicleform', array('activeVehicle' => $activeVehicle, 'openNewVehicle' => false)); ?>
                    </div>
                <?php
                    if ($view->userRights->isAllowed('ve', \Fado\Controller\RouterRights::$WRITE)) {
                ?>
                    <div class="tab-pane fade in active" id="VEHICLE_TAB_SHOP" role="tabpanel">
                    <?php

                    $view->includeTemplate('selectors/shop2vehicle', array('activeVehicle' =>  $activeVehicle, 'assignedShops' => $assignedShops, 'allShops' => $allShops));

                    ?>
                    </div>
                </div>
                <?php
                    }
                ?>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
