<?php
$formMessages = (array) json_decode(\Fado\Model\Cache::get('formStatus'));

if ($activeVehicle == null) {
    $activeVehicle = (array) json_decode(\Fado\Model\Cache::get('newFormData2'));
}

if (empty($activeVehicle) && empty($formMessages)) {
    $formMessages = array();
    $activeVehicle = array_fill_keys(VEHICLES_DATA_FIELDS, '');
}
if ($view->userRights->isAllowed('ve', \Fado\Controller\RouterRights::$READ)) {
    $disabled = 'disabled';
} else {
    $disabled = '';
}
?>
<div class="col-lg-6">
    <form method="POST" action="<?php echo $view->getFullLink(); ?>">
        <input type="hidden" name="id" value="<?php echo $activeVehicle['sid']; ?>">
        <div class="form-group <?php echo (isset($formMessages['name'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('VEHICLES_LABEL_NAME'); ?></label>
            <?php if (isset($formMessages['name'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['name']); ?></label>
            <?php } ?>
            <input name="name" class="form-control" placeholder="" value="<?php echo $activeVehicle['name']; ?>" <?php echo $disabled; ?>>
        </div>
        <div class="form-group <?php echo (isset($formMessages['street'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('VEHICLES_LABEL_MANUFACTURER'); ?></label>
            <?php if (isset($formMessages['street'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['manufacturer']); ?></label>
            <?php } ?>
            <input name="manufacturer" class="form-control" placeholder="" value="<?php echo $activeVehicle['manufacturer']; ?>" <?php echo $disabled; ?>>
        </div>
        <div class="form-group <?php echo (isset($formMessages['type'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('VEHICLES_LABEL_TYPE'); ?></label>
            <?php if (isset($formMessages['type'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['type']); ?></label>
            <?php } ?>
            <input name="type" class="form-control" placeholder="" value="<?php echo $activeVehicle['type']; ?>" <?php echo $disabled; ?>>
        </div>
        <div class="form-group <?php echo (isset($formMessages['construction_year'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('VEHICLES_LABEL_CONSTRUCTION_YEAR'); ?></label>
            <?php if (isset($formMessages['construction_year'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['construction_year']); ?></label>
            <?php } ?>
            <input name="construction_year" class="form-control" type="number" min="1" max="9999" placeholder="" value="<?php echo $activeVehicle['construction_year']; ?>" <?php echo $disabled; ?>>
        </div>
        <div class="form-group <?php echo (isset($formMessages['in_use'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('VEHICLES_LABEL_ACTIVE'); ?></label>
            <?php if (isset($formMessages['in_use'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['in_use']); ?></label>
            <?php } ?>
            <div class="checkbox-inline">
                <input name="in_use" type="checkbox" class="form-control" value="1" <?php echo ($activeVehicle['in_use'] == '1') ? 'checked="checked"' : ''; ?> <?php echo $disabled; ?>>
            </div>
        </div>
        <div class="form-group <?php echo (isset($formMessages['keynr'])) ? 'has-error' : ''; ?>">
            <label><?php echo $view->translate('VEHICLES_LABEL_KEYNR'); ?></label>
            <?php if (isset($formMessages['keynr'])) { ?>
            <label class="control-label" for="inputError"><?php echo $view->translate($formMessages['keynr']); ?></label>
            <?php } ?>
            <input name="keynr" class="form-control" placeholder="" value="<?php echo $activeVehicle['keynr']; ?>" <?php echo $disabled; ?>>
        </div>
        <button type="submit" name="submit" value="save_vehicle" class="btn btn-default" <?php echo $disabled; ?>><span class="glyphicon glyphicon-ok"></span> <?php echo $view->translate('SAVE'); ?></button>
        <?php if ($openNewVehicle != '1') { ?>
        <button type="button" name="delete" value="delete_vehicle" class="btn btn-default" data-toggle="modal" data-target="#modal-delete" <?php echo $disabled; ?>><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <?php echo $view->translate('DELETE'); ?></button>
        <?php } ?>
        <!-- <button type="reset" class="btn btn-default"><?php echo $view->translate('RESET'); ?></button> -->
    </form>
</div>
