<!DOCTYPE html>
<html lang="<?php echo $view->getActiveLanguage(); ?>">
<head>

    <title><?php echo $view->translate('PROGRAM_TITLE'); ?></title>


    <?php

    $view->includeTemplate('headersrc', array());

    ?>

    <!-- ckeditor JavaScript -->
    <script src="<?php echo $view->getHostLink(); ?>/vendor/ckeditor/ckeditor.js"></script>

    <!-- ckeditor config JavaScript -->
    <script src="<?php echo $view->getHostLink(); ?>/vendor/ckeditor/config.js"></script>

</head>

<body>
    <?php

    $view->includeTemplate('modaldelete', array());

    ?>
    <div id="wrapper">
        <?php

        $view->includeTemplate('navbar', array());

        ?>
        <div id="page-wrapper">
            <div class="row">
                <div class="colh1-lg-12">
                    <div class="panel"></div>
                </div>
            </div>
            <div class="row">
                <?php
                if (\Fado\Model\Cache::get('message') != '') {
                ?>
                <div class="col-lg-12">
                    <p>
                        <button type="button" class="btn btn-outline btn-danger"><?php echo $view->translate(\Fado\Model\Cache::get('message')); ?></button>
                    </p>
                </div>
                <?php
                }
                ?>
            </div>
                <?php
                $openNewItem = \Fado\Model\Cache::get('openNewItemForm');
                $view->includeTemplate('warehouseitemstable', array('items' => $items, 'allShops' => $allShops));
                ?>
            <div class="row" id="add-item-panel" style="<?php echo ($openNewItem == '1') ? '' : 'display: none'; ?>">
                <div class="col-lg-12">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <?php echo $view->translate('WAREHOUSE_PANEL_HEADING'); ?>
                            <div class="input-group pull-right">
                                <form>
                                    <span class="input-group-btn">
                                        <button type="button" id="close-add-item" class="btn btn-xs btn-secondary btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
                                    </span>
                                </form>
                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                        <?php
                            $view->includeTemplate('warehouseitemsform', array('activeItem' => null, 'allShops' => $allShops, 'openNewItem' => 1));
                        ?>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <?php
            $activeItem = $items->current();
            if ($items->getActivePos() >= 0 && $openNewItem != '1') {
               $view->includeTemplate('warehouseitemstabs', array('activeItem' => $activeItem, 'items' => $items, 'allShops' => $allShops, 'openNewItem' => $openNewItem));
            }
            ?>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <script>

       CKEDITOR.replace('editor-1');
       CKEDITOR.replace('editor-new');

        $('a[href*="item=<?php echo $items->current()['sid']; ?>"]').on('click', function(e) {
            $('#add-item-panel').css('display', 'none');
            $('#item-panel').css('display', 'block');
        });

        $('#add-wa, #close-add-item').on('click', function(e) {
            e.preventDefault();
            $('#add-item-panel, #item-panel').each(function() {
                $(this).toggle();
            });
        });

        $('#modal-delete').on('show.bs.modal', function(e) {
            var activeForm = $(e.relatedTarget.form)
            var formInput = activeForm.serializeArray();
            formInput.push({name: 'delete', value: 'delete_item'});
            $('button#modal-confirm-delete').on('click', function(e) {
                $.ajax({
                    url: activeForm.action,
                    type: 'POST',
                    data: formInput,
                    success: function(data){
                        document.open();
                        document.write(data);
                        document.close();
                    }
                });
            });
         });
     </script>

</body>

</html>
