<label><?php echo $view->translate($label); ?></label>
<div id="<?php echo $name; ?>" class="slider-weekday-container">
    <svg class="slider-weekday" xmlns="http://www.w3.org/2000/svg" version="1.1" width="600" height="5" viewBox="0 0 600 5">
        <rect x="0" y="0" width="600px" height="2px" fill="#d7d7d7" />
    </svg>
    <svg class="slider-start-weekday" style="margin-left: 0px;" xmlns="http://www.w3.org/2000/svg" version="1.1" width="5" height="40" viewBox="0 0 5 40">
        <rect x="0" y="0" width="5px" height="40px" fill="#2ca100" />
    </svg>
    <svg class="slider-end-weekday" style="margin-left: 600px;" xmlns="http://www.w3.org/2000/svg" version="1.1" width="5" height="40" viewBox="0 0 5 40">
        <rect x="0" y="0" width="5px" height="40px" fill="#2398a5" />
    </svg>
    <span class="range"></span>
    <input type="hidden" name="<?php echo $name; ?>" class="input" value="">
</div>
